// Registering, Authorization
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGOUT = 'LOGOUT'

// RapidAPI/NBA Related
export const GET_ALL_NBA_PLAYERS = 'GET_ALL_NBA_PLAYERS'
export const GET_ALL_NBA_TEAMS = 'GET_ALL_NBA_TEAMS'
export const GET_NBA_TEAM = 'GET_NBA_TEAM'

// Fantasy Related
export const CREATE_NEW_LEAGUE = 'CREATE_NEW_LEAGUE'
export const CLEAR_LEAGUES = 'CLEAR_LEAGUES'
export const LOAD_USERS_LEAGUES = 'LOAD_USERS_LEAGUES'
export const CREATE_NEW_FANTASY_TEAM = 'CREATE_NEW_FANTASY_TEAM'
export const LOAD_USERS_FANTASY_TEAMS = 'LOAD_USERS_FANTASY_TEAMS'
export const LOAD_USERS_MANAGED_LEAGUES = 'LOAD_USERS_MANAGED_LEAGUES'
export const ADD_NEW_LEAGUE_MANAGER = 'ADD_NEW_LEAGUE_MANAGER'